import { type DemoContextTree, exception, file, folder, listing, privacyNote, teamFile } from "./treeHelpers";

// ── @public-worship — shared, several members ────────────────────────────────

export const PUBLIC_WORSHIP_TREE: DemoContextTree = {
  listings: {
    "": listing("", "team", [
      folder("0-inbox", "team"),
      folder("1-projects", "team"),
      folder("2-areas", "team"),
      folder("3-resources", "team"),
      folder("4-archive", "team"),
      file("index.md", { visibility: "team", inherited: "team" }),
      file("privacy.md", { readOnly: true }),
    ]),
    "0-inbox": listing("0-inbox", "team", [
      teamFile("0-inbox/fwd-bandshell-permit.md"),
    ]),
    "1-projects": listing("1-projects", "team", [
      teamFile("1-projects/ltn-2026.md"),
      teamFile("1-projects/dc-chapter.md"),
      teamFile("1-projects/academy-pw-101.md"),
      exception("1-projects/fiscal-sponsorship.md", "private", "team"),
    ]),
    "2-areas": listing("2-areas", "team", [
      teamFile("2-areas/org-chart.md"),
      teamFile("2-areas/financial-transparency.md"),
      teamFile("2-areas/worship-with-strangers.md"),
    ]),
    "3-resources": listing("3-resources", "team", [
      teamFile("3-resources/doxology-framework.md"),
      teamFile("3-resources/mission.md"),
    ]),
  },
  notes: {
    "index.md": [
      "# Public Worship",
      "",
      "A Christian nonprofit in New York City, founded September 2024 and",
      "operating under Global Echo Charitable's 501(c)(3).",
      "",
      "Six people can read this workspace. Everything in it is team by",
      "default — the exceptions are the two or three things that are not",
      "ours to publish yet.",
      "",
    ].join("\n"),
    "0-inbox/fwd-bandshell-permit.md": [
      "---",
      "source: email",
      "received: 2026-08-25",
      "---",
      "",
      "# Fwd: Central Park Bandshell — permit window",
      "",
      "Forwarded in through the ingestion address. Naumburg Bandshell,",
      "3–6 PM. Someone please turn this into a task on LTN 2026.",
      "",
    ].join("\n"),
    "1-projects/ltn-2026.md": [
      "---",
      "updated: 2026-08-19",
      "status: active",
      "---",
      "",
      "# LTN 2026",
      "",
      "Central Park Bandshell, 3–6 PM, planning for ~500 people.",
      "",
      "Load-in at noon, sound check 2 PM, doors 2:45. The rider assumes",
      "we bring our own PA; the amplification cap on the permit is the",
      "open question.",
      "",
      "Presence over performance applies to the production too — the rig",
      "should be invisible from the lawn.",
      "",
    ].join("\n"),
    "1-projects/dc-chapter.md": [
      "---",
      "updated: 2026-08-18",
      "status: discussing",
      "---",
      "",
      "# Chapter model — DC next",
      "",
      "A chapter runs its own gatherings on the shared format, under the",
      "same fiscal sponsor, with its own local leadership on the org",
      "chart. DC is the one being discussed.",
      "",
    ].join("\n"),
    "1-projects/academy-pw-101.md": [
      "---",
      "updated: 2026-08-11",
      "---",
      "",
      "# Public Worship Academy — PW 101",
      "",
      "Organised in three movements:",
      "",
      "- **The Heart** — why we sing at all, and to whom.",
      "- **The Craft** — the musicianship the room deserves.",
      "- **The Witness** — what a gathering says to someone who",
      "  wandered in.",
      "",
      "PW 101 is the prerequisite for leading anywhere, chapters",
      "included.",
      "",
    ].join("\n"),
    "1-projects/fiscal-sponsorship.md": [
      "---",
      "visibility: private",
      "---",
      "",
      "# Fiscal sponsorship",
      "",
      "The one exception in this folder. Correspondence with Global Echo",
      "Charitable about the sponsorship agreement stays private until the",
      "terms are settled — then it moves into the open like everything",
      "else.",
      "",
    ].join("\n"),
    "2-areas/org-chart.md": [
      "# Org chart",
      "",
      "Executive Director (Seyi) → Music, Production, Formation,",
      "Operations. Each lead holds a seat; a seat carries duties rather",
      "than a person's name, so a handover changes one field.",
      "",
      "Chapters attach here: a chapter lead reports into Formation for",
      "the format and into Operations for the money.",
      "",
    ].join("\n"),
    "2-areas/financial-transparency.md": [
      "# Financial transparency",
      "",
      "Donors can inspect the ledger at the transaction level. Not a",
      "summary, not a pie chart — the actual rows, with what each one",
      "bought.",
      "",
      "The rule is that anything we would not be willing to show a donor",
      "line by line is something we should not be spending on.",
      "",
    ].join("\n"),
    "2-areas/worship-with-strangers.md": [
      "# Worship With Strangers",
      "",
      "A public, participatory format. The room is the choir; the band",
      "accompanies it. Nothing is performed at people.",
      "",
      "It is the format a chapter runs, which is why it lives in areas",
      "rather than projects — it does not finish.",
      "",
    ].join("\n"),
    "3-resources/doxology-framework.md": [
      "# The doxology framework",
      "",
      "How we evaluate a song before it goes in a set.",
      "",
      "1. **Who is it addressed to?** Doxology is sung *to* God.",
      "2. **Could the room mean it?** If it only works performed by the",
      "   person who wrote it, it is a concert piece.",
      "3. **Is it true?** Not \"is it moving\" — true.",
      "",
    ].join("\n"),
    "3-resources/mission.md": [
      "# Mission",
      "",
      "Matthew 13. The sower does the same thing everywhere; the",
      "difference is the ground. We are not trying to produce a harvest —",
      "we are trying to be somewhere one is possible.",
      "",
      "House shorthand: **presence over performance**.",
      "",
    ].join("\n"),
    "privacy.md": privacyNote(
      [
        "default_visibility: team",
        "",
        "folder_defaults:",
        "  0-inbox: team",
        "  1-projects: team",
        "  2-areas: team",
        "  3-resources: team",
        "  4-archive: team",
        "",
        "note_overrides:",
        "  1-projects/fiscal-sponsorship.md: private",
      ].join("\n"),
    ),
  },
  defaultSelection: "1-projects/ltn-2026.md",
  defaultExpanded: ["1-projects"],
  readOnlyReason: "This is a demo. Sign in to edit your own workspace.",
};
