import { noteHref, safeNotePath, slugFromSegment } from "./nav";

/**
 * The link format a connected agent can hand a person.
 *
 * ## The problem it exists for
 *
 * The console's own address for a note is `/console/@supa?note=<encoded path>`
 * — see `noteHref`. It is a fine URL for a browser and a bad one for anything
 * else to *produce*: the note rides in a query parameter, percent-encoded
 * whole, so a client writing one by hand has to know to encode the slashes and
 * a person reading one cannot see the note's name. What clients actually
 * produce, given the app's scheme, is the shape that reads like a path:
 *
 *     context://note/@supa/1-projects/context-lc-file-page-persistence/overview.md
 *
 * That exact URL, generated by ChatGPT on 2026-09-03, opened the app and
 * rendered Expo Router's **Unmatched Route** screen, because no route matched
 * `note/…`. It is kept as a fixture in `__tests__/noteLink.test.ts`.
 *
 * So this module makes that shape a real grammar rather than a guess: one
 * parser — `noteAddressFromSegments` for what Expo Router hands a route,
 * `noteAddressFromLink` for a raw URL — and one builder for the path, used by
 * the dead-end screen to show the shape it expects, so the example a person is
 * given cannot drift from the grammar that rejected them.
 *
 * **There is deliberately no builder for the `context://` form.** Nothing in
 * this app emits one: the thing that hands people links to notes is the
 * gateway, in `apps/mcp`, and a writer here would be a second implementation
 * of the grammar with no caller — checked only by a test asserting that our
 * copy agrees with itself. When the gateway starts emitting links, the grammar
 * moves to `packages/shared` and gets its writer there.
 *
 * ## Two formats, and which one is canonical
 *
 * **`/console/@slug?note=…` stays canonical.** It is what `teamShareLink`
 * copies, what survives sign-in (`attemptedHrefFrom` reads it off
 * `window.location`), and what a bookmark or a pasted URL restores — the whole
 * reason a file page is route-backed at all. `/note/@slug/<path>` is a *link*
 * format: the readable one an agent emits, which redirects to the canonical one
 * the moment it is opened. Both are accepted forever; only one is produced by
 * the app.
 *
 * ## Why the first segment is the literal word `note`
 *
 * On native, `context://note/@supa/x.md` reaches Expo Router through
 * `extractExactPathFromURL`, which builds `new URL(url)` and then concatenates
 * `res.host + res.pathname`. For a URL with a scheme and `//`, **the first
 * segment is parsed as the host**, and a host is normalised: lowercased, and
 * punycoded if it is not ASCII. `note` survives that untouched, which is
 * exactly why the grammar puts a fixed ASCII keyword there and the
 * customer-chosen `@slug` behind it. `context://@supa/x.md` — the shape without
 * the keyword — would put a customer's name through host normalisation, and a
 * `@` in a host position is not something to hand to a URL parser at all.
 *
 * It also disambiguates the grammar for humans: without a fixed first segment,
 * `note/1-projects/foo.md` and a context genuinely called `1-projects` are the
 * same string.
 *
 * ## What it refuses
 *
 * The context segment must carry its `@`. Bare `note/supa/x.md` is refused
 * rather than read as a context called `supa`, for the ambiguity above. The
 * path goes through `safeNotePath`, the one rule every externally-supplied
 * bucket path in this app goes through — so a traversal segment smuggled
 * through percent-encoding (`%2e%2e`) is refused *after* decoding, which is the
 * only order that catches it.
 */

/** The fixed first segment. See the module comment for why it is a keyword. */
export const NOTE_LINK_SEGMENT = "note";

/** A note somebody linked to: which context, and where in its bucket. */
export interface NoteAddress {
  /** Undecorated — `supa`, never `@supa`. `contextSegment` adds the `@` back. */
  slug: string;
  path: string;
}

/**
 * The readable link to one note: `/note/@supa/1-projects/foo.md`.
 *
 * Each path segment is encoded on its own, so the slashes stay slashes and a
 * space or a `#` in somebody's filename does not end the path early. That is
 * the difference from `noteHref`, which encodes the whole path into one query
 * value.
 */
export function noteLinkPath(slug: string, path: string): string {
  const encoded = path.split("/").map(encodeURIComponent).join("/");
  /*
    The `@` is left literal. It is a legal path character (RFC 3986 allows it
    in a segment unescaped) and it is the one character in this URL that tells
    a reader they are looking at a context's name — `%40supa` is the same
    address and reads like machinery. The parser accepts both.
  */
  const context = `@${encodeURIComponent(slugFromSegment(slug))}`;
  return `/${NOTE_LINK_SEGMENT}/${context}/${encoded}`;
}

/**
 * Read a note address out of the segments after `/note/`.
 *
 * **The segments are already decoded**, because this is what Expo Router hands
 * a catch-all route: `getParamValue` decodes the matched path and *then* splits
 * it on `/`. Decoding again here would turn a filename containing a literal
 * `%20` into one containing a space, and — worse — would give a crafted link
 * two passes to work with, which is how `%252e%252e` becomes `..` after
 * validation has already been done. `noteAddressFromLink` is the entry point
 * for a raw, still-encoded URL.
 */
export function noteAddressFromSegments(
  segments: readonly string[],
): NoteAddress | null {
  const [head, ...rest] = segments;
  if (head === undefined || rest.length === 0) return null;

  // The `@` is required. See "What it refuses" in the module comment.
  if (!head.startsWith("@")) return null;
  const slug = slugFromSegment(head);
  if (slug === "") return null;

  const path = safeNotePath(rest.join("/"));
  if (path === null) return null;
  return { slug, path };
}

/**
 * Read a note address out of a raw link, still percent-encoded.
 *
 * Every shape the product has to accept goes through here:
 *
 *   - `context://note/@supa/1-projects/foo.md` — what a phone receives.
 *   - `https://context.lc/note/@supa/1-projects/foo.md` — the same link in a
 *     browser, and what an agent should emit for somebody on a desktop.
 *   - `/note/@supa/1-projects/foo.md` and `note/@supa/…` — the in-app path,
 *     with and without the root; a native deep link arrives without one
 *     (`extractExpoPathFromURL` strips it).
 *
 * **`http(s)` loses an origin; the app scheme loses only the scheme.** That
 * asymmetry is the whole reason this is not `new URL(...)`: for `https://` the
 * segment after `//` really is a host and the path starts after it, while for
 * `context://` the same position holds the grammar's first path segment. A URL
 * parser applies the first rule to both and swallows the keyword.
 *
 * Decoding is per segment and happens **before** validation, which is the only
 * order that catches a traversal segment wearing an escape: `%2e%2e` is not
 * `..` until it is decoded, and `safeNotePath` is looking for `..`.
 */
export function noteAddressFromLink(link: string): NoteAddress | null {
  const withoutOrigin = /^https?:\/\//i.test(link)
    ? link.replace(/^https?:\/\/[^/]*/i, "")
    : link.replace(/^[a-zA-Z][a-zA-Z0-9+.-]*:\/\//, "");
  const withoutQuery = withoutOrigin.split("?")[0]!.split("#")[0]!;
  const segments = withoutQuery.split("/").filter((segment) => segment !== "");
  if (segments[0] !== NOTE_LINK_SEGMENT) return null;
  return noteAddressFromSegments(segments.slice(1).map(safeDecode));
}

/** Where a note link lands: the canonical console URL for that note. */
export function canonicalHrefFor(address: NoteAddress): string {
  return noteHref(address.slug, address.path);
}

/** A malformed escape is somebody's hand-edited URL, not a crash. */
function safeDecode(segment: string): string {
  try {
    return decodeURIComponent(segment);
  } catch {
    return segment;
  }
}
