import { afterEach, describe, expect, test } from "@jest/globals";
import { getFunctionName } from "convex/server";
import type { TranscriptSegment } from "../features/meetings/protocol";
import {
  TRANSCRIBE_CHUNK,
  cloudTranscriber,
  fakeTranscriber,
  resolveTranscriber,
  setTranscriber,
  setTranscriptionClient,
  type ActionRunner,
  type TranscribeChunkArgs,
} from "../features/meetings/capture/transcriber";

/**
 * The seam between "a chunk of audio" and "words", and the two promises it
 * keeps.
 *
 * ## The action is named, not reached for
 *
 * `functions/meetings/transcribe:transcribeChunk` is built in the control plane
 * to exactly the contract in `transcriber.ts`. It is referenced by
 * `makeFunctionReference` rather than through the generated `api` tree for a
 * reason that is about deploys rather than taste: `_generated/api.d.ts` is
 * regenerated by `npx convex dev`, so a checkout whose generated types predate
 * the action would fail to compile — and hand-editing `_generated/` to fix that
 * is never the answer. The path string is therefore load-bearing, and this file
 * pins it: a typo there is a runtime "function not found" on somebody's first
 * meeting, and nothing in the type system would have said a word.
 *
 * ## `speaker` is null, and it is null *here*
 *
 * Whisper does no diarization and gives no per-segment confidence. Both fields
 * are nullable in the protocol for exactly that reason, and this boundary is
 * where the app refuses to carry a label it did not hear — including one the
 * action might start sending after somebody swaps the engine. A note that says
 * who said something, when nothing knew, is a worse artifact than one that does
 * not say.
 *
 * ## The sabotage record
 *
 * Broken deliberately, all three capture suites run together (54 tests),
 * reverted:
 *
 *  - the action path changed to `functions/meetings/transcribe:transcribe`:
 *    1 failure, **"the action is the one the control plane built"**. Nothing
 *    else in the repo would have said a word — which is the whole reason a
 *    string is pinned by a test.
 *  - `intoSegment` passing `speaker` through: 3 failures — **"a speaker the
 *    engine never heard is refused"** here, and **"speaker is null on every
 *    segment that reaches a listener"** in *both* capture suites. That spread
 *    is the argument for enforcing it at one boundary rather than in three
 *    recorders.
 *  - `resolveTranscriber` preferring the installed client over a substituted
 *    transcriber: 1 failure, **"a substituted transcriber wins"**. Only one,
 *    because no other test installs a client — and that is exactly why this
 *    order needs its own assertion: the day something does install one, a
 *    reversed precedence would put the whole suite on the network with no
 *    other test noticing.
 */

const SEGMENT: TranscriptSegment = {
  id: "seg-1",
  startMs: 20_000,
  endMs: 21_500,
  text: "Let's ship it.",
  speaker: null,
  channel: "mic",
  confidence: null,
};

const CHUNK: TranscribeChunkArgs = {
  audioBase64: "YWJj",
  mimeType: "audio/mp4",
  chunkId: "1757095200000-1",
  offsetMs: 20_000,
  durationMs: 20_000,
};

/** A client that records what it was asked and answers with what it was given. */
function stubClient(answer: TranscriptSegment[]): ActionRunner & { calls: unknown[][] } {
  const calls: unknown[][] = [];
  return {
    calls,
    async action(reference, args) {
      calls.push([reference, args]);
      return { segments: answer };
    },
  };
}

afterEach(() => {
  setTranscriber(null);
  setTranscriptionClient(null);
});

describe("the action reference", () => {
  test("the action is the one the control plane built", () => {
    expect(getFunctionName(TRANSCRIBE_CHUNK)).toBe(
      "functions/meetings/transcribe:transcribeChunk",
    );
  });
});

describe("the cloud transcriber", () => {
  test("it says where the words are produced", () => {
    expect(cloudTranscriber(stubClient([])).transcribesAt).toBe("cloud");
  });

  test("the chunk crosses unchanged", async () => {
    const client = stubClient([SEGMENT]);
    await cloudTranscriber(client).transcribe(CHUNK);
    expect(client.calls).toHaveLength(1);
    expect(client.calls[0][0]).toBe(TRANSCRIBE_CHUNK);
    expect(client.calls[0][1]).toEqual(CHUNK);
  });

  test("segments come back as the action offset them, untouched", async () => {
    const segments = await cloudTranscriber(stubClient([SEGMENT])).transcribe(CHUNK);
    // The offsetting happens once, on the side that also knows what was said
    // inside the chunk. Adding `offsetMs` again here would put every line of a
    // forty-minute meeting twice as far along as it belongs.
    expect(segments[0].startMs).toBe(20_000);
    expect(segments[0].endMs).toBe(21_500);
    expect(segments[0].text).toBe("Let's ship it.");
  });

  /**
   * The one field this boundary rewrites, and the reason it does.
   */
  test("a speaker the engine never heard is refused", async () => {
    const segments = await cloudTranscriber(
      stubClient([{ ...SEGMENT, speaker: "Seyi" }]),
    ).transcribe(CHUNK);
    expect(segments[0].speaker).toBeNull();
  });

  test("a confidence that is not a number is null rather than a guess", async () => {
    const segments = await cloudTranscriber(
      stubClient([
        { ...SEGMENT, confidence: undefined as unknown as null },
        { ...SEGMENT, id: "seg-2", confidence: 0.42 },
      ]),
    ).transcribe(CHUNK);
    // Not 0 — which reads as "certainly wrong" — and not 1.
    expect(segments[0].confidence).toBeNull();
    // A real number the engine did give survives.
    expect(segments[1].confidence).toBe(0.42);
  });

  test("a channel nobody recognises is the microphone, which is what it was", async () => {
    const segments = await cloudTranscriber(
      stubClient([{ ...SEGMENT, channel: "speaker" as TranscriptSegment["channel"] }]),
    ).transcribe(CHUNK);
    expect(segments[0].channel).toBe("mic");
  });

  test("an action that answers with nothing is not a crash", async () => {
    const segments = await cloudTranscriber(stubClient([])).transcribe(CHUNK);
    expect(segments).toEqual([]);
  });
});

describe("the module seam", () => {
  /**
   * `createRecorder(platform)` takes one argument and keeps taking one, so the
   * recorders resolve their transcriber from here. Nothing above `capture/`
   * knows cloud transcription exists, and no test in this repo has to mock
   * `convex/react` to stay off the network.
   */
  test("nothing is resolved until something is installed", () => {
    expect(resolveTranscriber()).toBeNull();
  });

  test("an installed client becomes a cloud transcriber", () => {
    setTranscriptionClient(stubClient([]));
    expect(resolveTranscriber()?.transcribesAt).toBe("cloud");
  });

  test("a substituted transcriber wins", async () => {
    const client = stubClient([SEGMENT]);
    setTranscriptionClient(client);
    const fake = fakeTranscriber();
    setTranscriber(fake);

    await resolveTranscriber()?.transcribe(CHUNK);
    expect(fake.chunks).toHaveLength(1);
    expect(client.calls).toEqual([]);
  });

  /**
   * Forgetting the client matters on a sign-out or a context switch: a recorder
   * still holding the previous session's client would be shipping one person's
   * audio under another person's credentials.
   */
  test("forgetting the client forgets the transcriber", () => {
    setTranscriptionClient(stubClient([]));
    setTranscriptionClient(null);
    expect(resolveTranscriber()).toBeNull();
  });
});

describe("the fake", () => {
  test("it records what it was handed and answers what it was told to", async () => {
    const fake = fakeTranscriber();
    fake.answerWith([SEGMENT]);
    const segments = await fake.transcribe(CHUNK);
    expect(fake.chunks).toEqual([CHUNK]);
    expect(segments).toHaveLength(1);
  });

  test("it can refuse once, the way a request that timed out does", async () => {
    const fake = fakeTranscriber();
    fake.refuse("the network went away");
    await expect(fake.transcribe(CHUNK)).rejects.toThrow("the network went away");
    await expect(fake.transcribe(CHUNK)).resolves.toEqual([]);
  });
});
