import { describe, expect, test } from "@jest/globals";
import { extractExpoPathFromURL } from "expo-router/build/fork/extractPathFromURL";
import {
  NOTE_LINK_SEGMENT,
  canonicalHrefFor,
  noteAddressFromLink,
  noteAddressFromSegments,
  noteLinkPath,
} from "../features/console/noteLink";

/**
 * **A note link from ChatGPT opened the app and said "Unmatched Route".**
 *
 * Observed on iOS on 2026-09-03. The link is the fixture below, and it is kept
 * verbatim rather than reconstructed, because the point of it is that it was
 * written by something outside this codebase: the shape a client reaches for,
 * given a registered scheme and a note with a path.
 *
 * ## Why the deep-link half runs expo-router's own extractor
 *
 * The path a route is matched against is not the URL. On native it is whatever
 * `extractExactPathFromURL` makes of it, and that function does something
 * surprising and load-bearing: for a custom scheme it builds `new URL(url)` and
 * concatenates **`res.host` + `res.pathname`**, so the first segment after
 * `//` is parsed as a *host* — lowercased, punycoded if not ASCII — and then
 * pasted back on the front of the path.
 *
 * The entire reason this grammar puts the fixed keyword `note` there, and the
 * customer-chosen `@slug` behind it, is that assertion. Writing it down in a
 * comment would be a claim about somebody else's library; importing the real
 * function makes it a test, and an expo upgrade that changes the rule fails
 * here rather than on a phone.
 *
 * `expo-router/build/…` is a build artifact, and importing one is a liberty.
 * It is taken deliberately and only here: this is the seam where a dependency's
 * behaviour *is* the requirement, and the alternative — reimplementing the
 * extraction in the test — would assert that our copy of it agrees with itself.
 */

/** Generated by ChatGPT, followed on iOS, landed on Unmatched Route. */
const FROM_CHATGPT =
  "context://note/@supa/1-projects/context-lc-file-page-persistence/overview.md";

const SLUG = "supa";
const PATH = "1-projects/context-lc-file-page-persistence/overview.md";
/** Taken from the fixture, so the config assertion below is about *that* link. */
const SCHEME = FROM_CHATGPT.split("://")[0]!;

/**
 * What Expo Router hands a catch-all route, given a URL.
 *
 * `extractExpoPathFromURL` is the native half; the split and decode is what
 * `getParamValue` does to the matched segment (decode, then split on `/`),
 * which is why `noteAddressFromSegments` must not decode again.
 */
function segmentsFor(url: string): string[] {
  return extractExpoPathFromURL([], url)
    .split("?")[0]!
    .split("/")
    .filter((segment) => segment !== "")
    .map((segment) => decodeURIComponent(segment));
}

describe("the link an agent hands somebody", () => {
  test("the ChatGPT link resolves to the note it names", () => {
    expect(noteAddressFromLink(FROM_CHATGPT)).toEqual({ slug: SLUG, path: PATH });
  });

  test("…and it does so through expo-router's own path extraction", () => {
    // The regression in the form the app actually meets it: a URL, through the
    // library's extractor, into the segments a route receives.
    const segments = segmentsFor(FROM_CHATGPT);
    expect(segments[0]).toBe(NOTE_LINK_SEGMENT);
    expect(noteAddressFromSegments(segments.slice(1))).toEqual({ slug: SLUG, path: PATH });
  });

  test("the keyword survives being read as a host, which is why it is a keyword", () => {
    // If this ever fails, the grammar's first segment is being normalised and
    // the module comment's reasoning needs revisiting — not the fixture.
    expect(segmentsFor(`${SCHEME}://note/@a/b.md`)[0]).toBe("note");
  });

  test("the path the app builds is the path in that link", () => {
    // The builder writes the shape the dead-end screen shows somebody; the
    // fixture is what a client wrote without being told. They must agree.
    expect(noteLinkPath(SLUG, PATH)).toBe(`/note/@supa/${PATH}`);
    expect(`${SCHEME}:/${noteLinkPath(SLUG, PATH)}`).toBe(FROM_CHATGPT);
  });

  test("the canonical destination is the console URL, encoded whole", () => {
    expect(canonicalHrefFor({ slug: SLUG, path: PATH })).toBe(
      `/console/@supa?note=${encodeURIComponent(PATH)}`,
    );
  });

  test("an `@` in the slug may be escaped or not", () => {
    expect(noteAddressFromLink("context://note/%40supa/a.md")).toEqual({
      slug: SLUG,
      path: "a.md",
    });
  });

  test("spaces, deep folders and unicode survive the round trip", () => {
    const awkward = "3-resources/reading notes/Café — 2026.md";
    const link = `${SCHEME}:/${noteLinkPath(SLUG, awkward)}`;
    expect(link).not.toContain(" ");
    expect(noteAddressFromLink(link)).toEqual({ slug: SLUG, path: awkward });
    expect(noteAddressFromSegments(segmentsFor(link).slice(1))).toEqual({
      slug: SLUG,
      path: awkward,
    });
  });

  test("the `.md` suffix is preserved, never stripped as an extension", () => {
    expect(noteAddressFromLink("context://note/@a/b/c.md")?.path).toBe("b/c.md");
  });

  test("a web link loses its origin and keeps its path", () => {
    expect(noteAddressFromLink(`https://context.lc/note/@supa/${PATH}`)).toEqual({
      slug: SLUG,
      path: PATH,
    });
    // A self-hoster's domain, and a dev server's port.
    expect(noteAddressFromLink("http://localhost:8081/note/@a/b.md")).toEqual({
      slug: "a",
      path: "b.md",
    });
  });

  test("an in-app path works with or without its leading slash", () => {
    expect(noteAddressFromLink("/note/@a/b.md")).toEqual({ slug: "a", path: "b.md" });
    expect(noteAddressFromLink("note/@a/b.md")).toEqual({ slug: "a", path: "b.md" });
  });
});

describe("what a note link is refused for", () => {
  /*
    This repository is public, and a link is the one thing in the product a
    stranger can hand a signed-in person. Every refusal here ends up as a path
    in a request to somebody's bucket if it is not one.
  */
  test("a traversal segment, including one wearing an escape", () => {
    expect(noteAddressFromLink("context://note/@a/../../etc/passwd")).toBeNull();
    expect(noteAddressFromLink("context://note/@a/%2e%2e/%2e%2e/secrets.md")).toBeNull();
    expect(noteAddressFromSegments(["@a", "..", "b.md"])).toBeNull();
  });

  test("a rooted path", () => {
    expect(noteAddressFromSegments(["@a", "", "b.md"])).toBeNull();
  });

  test("a control character", () => {
    /*
      Spelled as an escape, never typed. A raw control byte in a source file
      makes the file binary to `grep` and invisible in every diff it appears
      in — the same rule `offline/keys.ts` states for its separator, and this
      test carried one for about ten minutes.
    */
    expect(noteAddressFromSegments(["@a", "b\u0007.md"])).toBeNull();
    expect(noteAddressFromLink("context://note/@a/b%00.md")).toBeNull();
  });

  test("a backslash, which some parsers normalise to a slash", () => {
    expect(noteAddressFromLink("context://note/@a/b%5C..%5Cc.md")).toBeNull();
  });

  test("a context segment with no `@`", () => {
    // Ambiguous with a path, and reading it as a context is how a link to
    // `note/1-projects/foo.md` opens a context called `1-projects`.
    expect(noteAddressFromLink("context://note/supa/a.md")).toBeNull();
  });

  test("no path at all", () => {
    expect(noteAddressFromLink("context://note/@supa")).toBeNull();
    expect(noteAddressFromSegments(["@supa"])).toBeNull();
    expect(noteAddressFromSegments([])).toBeNull();
  });

  test("a link that is not a note link", () => {
    expect(noteAddressFromLink("context://console/@supa")).toBeNull();
    expect(noteAddressFromLink("https://context.lc/s/token")).toBeNull();
    expect(noteAddressFromLink("")).toBeNull();
  });

  test("an empty context name", () => {
    expect(noteAddressFromSegments(["@", "a.md"])).toBeNull();
  });
});

describe("the binary registers the scheme this link arrives on", () => {
  test("app.config.js claims the fixture's scheme, on both platforms", () => {
    /*
      Everything above this point tests what happens *once* the URL reaches the
      router. Whether it reaches the router at all is decided by the operating
      system, from `scheme` in `app.config.js` — which ends up in `Info.plist`
      and in the Android intent filter. A mismatch fails silently and
      completely: the link opens nothing, on a device, with no error anywhere.

      Asserted against the scheme of the observed link rather than a constant of
      ours, so this is a claim about *that link* and not about our copy of a
      string agreeing with itself.
    */
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const config = require("../app.config.js")({ config: {} }) as {
      scheme?: string;
      android?: { intentFilters?: { data?: { scheme?: string }[] }[] };
    };
    expect(config.scheme).toBe(SCHEME);

    const androidSchemes = (config.android?.intentFilters ?? [])
      .flatMap((filter) => filter.data ?? [])
      .map((data) => data.scheme);
    expect(androidSchemes).toContain(SCHEME);
  });
});
