import { MEETING_ID_ALPHABET, MEETING_ID_LENGTH, MEETING_ID_PREFIX, isMeetingId } from "./protocol";

/**
 * Meeting ids, made on the device.
 *
 * The protocol fixes the shape — `mtg_` plus twenty lowercase base32
 * characters — and fixes it for a reason: the id is generated by the *client*
 * and is what makes every route idempotent. "The same session id upserts", so a
 * phone that lost signal mid-meeting re-sends under the id it already used and
 * the gateway recognises the meeting rather than creating a second one. An id
 * minted by the server would mean a meeting has no name until the first request
 * succeeds, which is exactly the request that fails on a train.
 *
 * The alphabet and the length are the contract's — `MEETING_ID_ALPHABET` and
 * `MEETING_ID_LENGTH`, which is also what `protocol.js` builds the regex from,
 * so there is one statement of what an id is rather than three. This file kept
 * its own copy of both, with a comment admitting nothing would notice them
 * drifting. `newMeetingId` still validates its own output against `isMeetingId`
 * before returning it, so a mistake here is caught on this device rather than
 * as a `meeting_invalid` from the gateway after somebody has already recorded
 * an hour.
 *
 * ## About the randomness
 *
 * A meeting id is an **identifier**, not a capability. Reaching a meeting needs
 * the workspace's own authentication; guessing an id gets nobody anything, and
 * the protocol's own `forbidden` code is the gateway saying so ("Session id
 * belongs to another workspace"). What the id has to be is *unique*, and 100
 * bits is unique enough that a person recording ten meetings a day would need
 * longer than the age of the universe to collide.
 *
 * So this prefers `crypto.getRandomValues` where the platform has it — a
 * browser, and any Hermes build with WebCrypto — and falls back to `Math.random`
 * where it does not. That fallback is stated rather than hidden because the
 * usual rule is the opposite one: anything that *is* a capability (a token, a
 * share link, a PKCE verifier) must never be allowed to reach it.
 *
 * `expo-crypto` is in `native-deps.json` `core` and would remove the fallback
 * on a phone. It is deliberately not imported: it ships ESM that this app's
 * jest setup cannot require (`transformIgnorePatterns` lets `expo` through, but
 * its `base64-js` dependency is not), so importing it here would make the whole
 * meetings feature untestable to buy strength this value does not need. When
 * the suite grows a native transform, this is a two-line change.
 */

const ALPHABET = MEETING_ID_ALPHABET;
const LENGTH = MEETING_ID_LENGTH;

/** Fills a byte array. Injected so a test can mint a known id. */
export type RandomBytes = (length: number) => Uint8Array;

export function newMeetingId(randomBytes: RandomBytes = defaultRandomBytes): string {
  const bytes = randomBytes(LENGTH);
  let id = MEETING_ID_PREFIX;
  for (let index = 0; index < LENGTH; index += 1) {
    // A mask rather than a modulo. 256 is a multiple of 32, so the two are
    // equivalent here — the mask says so at a glance, where a `% 32` invites
    // the reader to check for the modulo bias that a non-power-of-two alphabet
    // would have.
    id += ALPHABET[(bytes[index] ?? 0) & 31];
  }
  if (!isMeetingId(id)) {
    // Unreachable now that the alphabet, the length and the regex all come from
    // one place. Kept because the mask below is an assumption about the
    // alphabet's *size* that no import can carry: 256 is a multiple of 32, and
    // an alphabet that stopped being 32 characters long would silently start
    // producing ids the gateway refuses.
    throw new Error("newMeetingId produced an id the protocol would refuse");
  }
  return id;
}

function defaultRandomBytes(length: number): Uint8Array {
  const bytes = new Uint8Array(length);
  const webCrypto = globalThis.crypto;
  if (webCrypto !== undefined && typeof webCrypto.getRandomValues === "function") {
    webCrypto.getRandomValues(bytes);
    return bytes;
  }
  for (let index = 0; index < length; index += 1) {
    bytes[index] = Math.floor(Math.random() * 256);
  }
  return bytes;
}
